### ISSUE TITLE
Do you need to retrain the discriminator for each scene?

### ISSUE THREAD

**Issue by xzr52** [buaacyw/IT3D-text-to-3D#2]
I am very honored to have read your paper. I would like to ask a question:do you need to retrain the discriminator for each scene?

**Comment by buaacyw** [comment]
Thanks.
Yes, each scene is retrained. Resume from a discriminator trained in another scene won't help. 
Discriminator is randomly initialized for each scene.
The main insight is that with SDS loss, we don't need a strong Discriminator like EG3D. We only need the D to have knowledge about the distribution gap between the real dataset and the NeRF. So D in other scenes won't help.

**Comment by buaacyw** [comment]
EG3D resume from human face ckpts for cat face training because the information contained in the human face checkpoints holds valuable foundational knowledge. However, IT3D does not require foundational knowledge from D, as SDS can provide it.

**Comment by xzr52** [comment]
thank you very much for your answer
