### ISSUE TITLE
The following problems occurred when I wanted to generate mesh

### ISSUE THREAD

**Issue by xzr52** [buaacyw/IT3D-text-to-3D#4]
When I ran this command:  python main.py -O --text "a bunch of blue rose, highly detailed" --workspace rose_blue_ctn_dm  --gan --ctn --no_cam_D  --g_loss_decay_begin_step 5000 --g_loss_decay_step 5000  --init_with ckpts/rose_df_ep0200.pth --dmtet --init_color --real_save_path generated_dataset/rose_blue_ctn
halfway, I reported such an error, may I ask if there is any problem, or what conditions are not met.I would be very grateful if you could answer my question
==> [2023-08-27_15-47-13] Finished Epoch 470/20000. CPU=5.3GB, GPU=23.1GB.
==> [2023-08-27_15-47-13] Start Training rose_blue_ctn_dm Epoch 471/20000, lr=0.050000 ...
 11% 11/100 [00:03<00:26,  3.39it/s]Traceback (most recent call last):
  File "main.py", line 490, in <module>
    trainer.train(train_loader, valid_loader, test_loader, img2img_loader, max_epoch)
  File "/opt/data/private/image_to_3d/IT3D-text-to-3D-master/nerf/utils.py", line 1749, in train
    self.train_one_epoch(train_loader, max_epochs)
  File "/opt/data/private/image_to_3d/IT3D-text-to-3D-master/nerf/utils.py", line 2089, in train_one_epoch
    pred_rgbs, pred_depths, loss, reg_stats = self.train_step(data, save_guidance_path=None)
  File "/opt/data/private/image_to_3d/IT3D-text-to-3D-master/nerf/utils.py", line 1948, in train_step
    outputs = self.model.render(rays_o, rays_d, mvp, H, W, staged=False, perturb=True, bg_color=bg_color,
  File "/opt/data/private/image_to_3d/IT3D-text-to-3D-master/nerf/renderer.py", line 1172, in render
    results = self.run_dmtet(rays_o, rays_d, mvp, h, w, **kwargs)
  File "/opt/data/private/image_to_3d/IT3D-text-to-3D-master/nerf/renderer.py", line 906, in run_dmtet
    rast, _ = dr.rasterize(self.glctx, verts_clip, faces, (h, w))
  File "/root/anaconda3/envs/nerfart/lib/python3.8/site-packages/nvdiffrast-0.3.0-py3.8.egg/nvdiffrast/torch/ops.py", line 310, in rasterize
    return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
  File "/root/anaconda3/envs/nerfart/lib/python3.8/site-packages/nvdiffrast-0.3.0-py3.8.egg/nvdiffrast/torch/ops.py", line 248, in forward
    out, out_db = _get_plugin().rasterize_fwd_cuda(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
RuntimeError: instance mode - pos must have shape [>0, >0, 4]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/data/private/image_to_3d/IT3D-text-to-3D-master/main.py:490 in <module>                     │
│                                                                                                  │
│   487 │   │   │   img2img_loader = NeRFDataset(opt, device=device, type='test', H=512, W=512,    │
│   488 │   │   │   │   │   │   │   │   │     size=opt.img2img_view_num).dataloader(batch_size=1   │
│   489 │   │   │                                                                                  │
│ ❱ 490 │   │   │   trainer.train(train_loader, valid_loader, test_loader, img2img_loader, max_e   │
│   491 │   │   else:                                                                              │
│   492 │   │   │   trainer.train(train_loader, valid_loader, test_loader, max_epoch)              │
│   493                                                                                            │
│                                                                                                  │
│ /opt/data/private/image_to_3d/IT3D-text-to-3D-master/nerf/utils.py:1749 in train                 │
│                                                                                                  │
│   1746 │   │   │   │   self.test(test_loader)                                                    │
│   1747 │   │   │                                                                                 │
│   1748 │   │   │                                                                                 │
│ ❱ 1749 │   │   │   self.train_one_epoch(train_loader, max_epochs)                                │
│   1750 │   │                                                                                     │
│   1751 │   │   end_t = time.time()                                                               │
│   1752                                                                                           │
│                                                                                                  │
│ /opt/data/private/image_to_3d/IT3D-text-to-3D-master/nerf/utils.py:2089 in train_one_epoch       │
│                                                                                                  │
│   2086 │   │   │   # train G                                                                     │
│   2087 │   │   │   self.optimizer.zero_grad()                                                    │
│   2088 │   │   │   with torch.cuda.amp.autocast(enabled=self.fp16):                              │
│ ❱ 2089 │   │   │   │   pred_rgbs, pred_depths, loss, reg_stats = self.train_step(data, save_gui  │
│   2090 │   │   │   │   stats.update(reg_stats)                                                   │
│   2091 │   │   │   # hooked grad clipping for RGB space                                          │
│   2092 │   │   │   if self.opt.grad_clip_rgb >= 0: # F                                           │
│                                                                                                  │
│ /opt/data/private/image_to_3d/IT3D-text-to-3D-master/nerf/utils.py:1948 in train_step            │
│                                                                                                  │
│   1945 │   │   │   else:                                                                         │
│   1946 │   │   │   │   bg_color = torch.rand(3).to(self.device)  # single color random bg        │
│   1947 │   │                                                                                     │
│ ❱ 1948 │   │   outputs = self.model.render(rays_o, rays_d, mvp, H, W, staged=False, perturb=Tru  │
│   1949 │   │   │   │   │   │   │   │   │   ambient_ratio=ambient_ratio, shading=shading, binari  │
│   1950 │   │   pred_depth = outputs['depth'].reshape(B, 1, H, W)                                 │
│   1951 │   │   pred_mask = outputs['weights_sum'].reshape(B, 1, H, W)                            │
│                                                                                                  │
│ /opt/data/private/image_to_3d/IT3D-text-to-3D-master/nerf/renderer.py:1172 in render             │
│                                                                                                  │
│   1169 │   │   device = rays_o.device                                                            │
│   1170 │   │                                                                                     │
│   1171 │   │   if self.dmtet:                                                                    │
│ ❱ 1172 │   │   │   results = self.run_dmtet(rays_o, rays_d, mvp, h, w, **kwargs)                 │
│   1173 │   │   elif self.cuda_ray:                                                               │
│   1174 │   │   │   results = self.run_cuda(rays_o, rays_d, **kwargs)                             │
│   1175 │   │   elif self.taichi_ray:                                                             │
│                                                                                                  │
│ /opt/data/private/image_to_3d/IT3D-text-to-3D-master/nerf/renderer.py:906 in run_dmtet           │
│                                                                                                  │
│    903 │   │   verts_clip = torch.bmm(F.pad(verts, pad=(0, 1), mode='constant', value=1.0).unsq  │
│    904 │   │   │   │   │   │   │      mvp.permute(0,2,1)).float()  # [B, N, 4]                   │
│    905 │   │   # try:                                                                            │
│ ❱  906 │   │   rast, _ = dr.rasterize(self.glctx, verts_clip, faces, (h, w))                     │
│    907 │   │   # except Exception as e:                                                          │
│    908 │   │   #     print("here")                                                               │
│    909 │   │   alpha = (rast[..., 3:] > 0).float()                                               │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/nvdiffrast-0.3.0-py3.8.egg/nvdiffrast/t │
│ orch/ops.py:310 in rasterize                                                                     │
│                                                                                                  │
│   307 │   │   return RuntimeError("Cannot call rasterize() during depth peeling operation, use   │
│   308 │                                                                                          │
│   309 │   # Instantiate the function.                                                            │
│ ❱ 310 │   return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)         │
│   311                                                                                            │
│   312 #----------------------------------------------------------------------------              │
│   313 # Depth peeler context manager for rasterizing multiple depth layers.                      │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/nvdiffrast-0.3.0-py3.8.egg/nvdiffrast/t │
│ orch/ops.py:248 in forward                                                                       │
│                                                                                                  │
│   245 │   │   if isinstance(raster_ctx, RasterizeGLContext):                                     │
│   246 │   │   │   out, out_db = _get_plugin(gl=True).rasterize_fwd_gl(raster_ctx.cpp_wrapper,    │
│   247 │   │   else:                                                                              │
│ ❱ 248 │   │   │   out, out_db = _get_plugin().rasterize_fwd_cuda(raster_ctx.cpp_wrapper, pos,    │
│   249 │   │   ctx.save_for_backward(pos, tri, out)                                               │
│   250 │   │   ctx.saved_grad_db = grad_db                                                        │
│   251 │   │   return out, out_db                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: instance mode - pos must have shape [>0, >0, 4]

**Comment by buaacyw** [comment]
Yes. I also meet this problem. This issue persists in [Stable Dreamfusion Repo](https://github.com/ashawkey/stable-dreamfusion/issues/278). Sorry I still don't know how to solve it. 
Empirically, this happens at the early stage of the training or when the mesh has been over-trained. I think your case is the latter one. You should take a look at the wandb log and would find a nice result around 10K step:
![image](https://github.com/buaacyw/IT3D-text-to-3D/assets/52091468/e0a86131-799f-4795-ad7b-0bf78be29bbe)
