### ISSUE TITLE
About training epoch，how long will it take for the model to converge

### ISSUE THREAD

**Issue by MnKnight1** [buaacyw/IT3D-text-to-3D#6]
https://github.com/buaacyw/IT3D-text-to-3D/blob/3793c5fab54985ce25b7e183819f246ffab97d18/main.py#L485-L490

In the code,`max_epoch` is set to 2000 after `max_epoch *= 100`,so how long will it take for the model to converge? 
I read "**To ensure a fair comparison, we train the baseline method for 25K steps (1.5to 2.5GPU hours) to guarantee the full convergence of the 3D model**."in the paper.
But if `max_epoch` is set to 2000 ，the training time will be very long，because a epoch takes around 30 seconds （I use RTX3090）

_“==> [2023-09-10_09-27-59] Start Training jas_ctn Epoch 218/20000, lr=0.050000 ...
100% 100/100 [00:31<00:00,  3.20it/s]
==> [2023-09-10_09-28-31] Finished Epoch 218/20000. CPU=7.6GB, GPU=111.7GB.”_

**Comment by MnKnight1** [comment]
I have found the reason here，
https://github.com/buaacyw/IT3D-text-to-3D/issues/5#issuecomment-1696734864

but I have a new question：
**“To ensure a fair comparison, we train the baseline method for 25K steps (1.5to 2.5GPU hours) to guarantee the full convergence of the 3D model.”**
I found that the geometry of the object had changed (missing shape) at 300 epoch after resuming  from 200 epoch（ckpts you provide）**.Will it help to add shape prior loss?**
epoch200
https://github.com/buaacyw/IT3D-text-to-3D/assets/78358378/36beaba7-0182-44be-85a9-2b5dfbae8909

epoch300
https://github.com/buaacyw/IT3D-text-to-3D/assets/78358378/feb362af-c3c8-4592-8fd8-0b3443e910ab

**Comment by buaacyw** [comment]
That's weird. Are you using this command:
`python main.py -O --text "a bunch of white jasmine" --workspace jas_ctn --ckpt ckpts/jas_df_ep0200.pth --no_cam_D --gan --ctn --g_loss_decay_begin_step 25000 --real_save_path generated_dataset/jas_ctn
`
In the paper, all the datasets are generated with ControlNet. It looks like you are not using ControlNet for data generation. Please check your data generation samples in Wandb. Stable DIffusion Image-to-Image pipeline is much faster but always generates low quality dataset.

**Comment by buaacyw** [comment]
And sorry I will remove this *100. It's really a dummy implementation.

**Comment by MnKnight1** [comment]
First of all, thank you for your reply！
But I still have two question：
1.I retrained and made sure that `ctn_models/control_v11p_sd15_softedge.pth` was used. From 290 to 300 epoch, the problem of missing geometry is successfully reproduced.
290epoch

https://github.com/buaacyw/IT3D-text-to-3D/assets/78358378/a1bc8dd7-dead-4a8a-a2d3-392440a83ef8

300 epoch

https://github.com/buaacyw/IT3D-text-to-3D/assets/78358378/98f70361-665e-4f59-82a9-43377c3ce378


2.**During the coarse model phase**, I felt that the model I trained according to the default parameters of `main.py` was very different from the one you provided in terms of texture details( **over-smoothing** ). Is your coarse nerf model trained by stable dreamfusion? If so, would you please provide parameters for training coarse nerf? 
**During the refined model phase**， I think it is also due to the over-smoothing problem that the details are not realistic enough, not because of gan loss.
![QQ截图20230912181504](https://github.com/buaacyw/IT3D-text-to-3D/assets/78358378/9dad01b9-f200-4331-b9de-726152ae2589)

**Comment by MnKnight1** [comment]
All the problems are caused by using SD1.5, not SD2.1 (over-smoothing,missing geometry). Thank you for your help.
