### ISSUE TITLE
Where is scripts/install_ext.sh ?

### ISSUE THREAD

**Issue by 2018zhaizhijun** [buaacyw/IT3D-text-to-3D#7]
During installation, there is a `bash scripts/install_ext.sh` step, but it seems that `scripts/install_ext.sh` file is not in the project? Could you please tell me where to find it? Thanks!

**Comment by buaacyw** [comment]
Sorry I missed that file. Please check the new installation session.

**Comment by 2018zhaizhijun** [comment]
Thanks!
