### ISSUE TITLE
有没有人ubuntu 22.04 n卡3090安装成功的

### ISSUE THREAD

**Issue by Daniel-ccx** [buaacyw/IT3D-text-to-3D#9]
ubuntu 22.04
nvidia 3090
cuda tookit 12.2
nvcc 12.1

遇到的问题：
安装到raymarching ，需要pytorch 使用c++17编译。最后一次安装也是pytorch的问题。

求安装手册？
windows11 安装了1次，ubuntu安装了3次，都是各种版本不对应的问题

**Comment by Daniel-ccx** [comment]
`
/home/huan/anaconda3/envs/it3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py:425: UserWarning: There are no g++ version bounds defined for CUDA version 12.1
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building '_raymarching' extension
`

**Comment by Daniel-ccx** [comment]
`g++ -std=c++14 -E - </dev/null`

> cc1: warning: command-line option ‘-std=c++14’ is valid for C++/ObjC++ but not for C

`g++ -std=c++17 -E - </dev/null`

> cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C

**Comment by Daniel-ccx** [comment]
modify raymarching/setup.py
change c++14 to c++17
and here is compile result
`
Processing ./raymarching
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: raymarching
  Building wheel for raymarching (setup.py): started
  Building wheel for raymarching (setup.py): finished with status 'done'
  Created wheel for raymarching: filename=raymarching-0.0.0-cp38-cp38-linux_x86_64.whl size=2785156 sha256=0373156ac101f052714a6bffb8e43fd62dd9d79df8ff829da0385b7a31251676
  Stored in directory: /tmp/pip-ephem-wheel-cache-typymtb8/wheels/72/bb/f4/421dbbacafe4bf39faa88fc52a0e73f414cdcdafda655a89a4
Successfully built raymarching
Installing collected packages: raymarching
Successfully installed raymarching-0.0.0

`

**Comment by Daniel-ccx** [comment]
resolved

**Comment by wuweiyexiaomian** [comment]
![2e49a5cd2d0c251fd0b3a8300eb0978](https://github.com/buaacyw/IT3D-text-to-3D/assets/100900062/31f9d1c5-7e0b-46ce-a90a-0ef6b6a9601b)
请问这个怎么解决？
